### ISSUE TITLE
26th of May. The Minskins

### ISSUE THREAD

**Issue by WinterCore** [Bismarck-GM/Microverse-Using-Bootstrap#2]
The project looks amazing. Well done on using the `sticky` css property on the first section.
and here's a cat
<pre>
 ,_     _
 |\\_,-~/
 / _  _ |    ,--.
(  @  @ )   / ,-'
 \  _T_/-._( (
 /         `. \
|         _  \ |
 \ \ ,  /      |
  || |-_\__   /
 ((_/`(____,-'
</pre>

**Comment by Bismarck-GM** [comment]
<pre>
    ___
 __/_  `.  .-"""-.
 \_,` | \-'  /   )`-')
  "") `"`    \  ((`"`
 ___Y  ,    .'7 /|
(_,___/...-` (_/_/ 
</pre>
